on: [push]
name: CI

jobs:
  test:
    name: test solvers
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'
      - name: Run tests
        run: |
          python3 check_all.py
